### PR TITLE
Several improvements

### PR DESCRIPTION
**Pull request by taliastocks**
- Faster copying of C array to ImageData.
- Yield the main thread after decoding each image of an animation.
- Allow separating image download from image decoding.
- Use `exports` instead of `window` so this can be used as a CommonJS-like module. Note that by default, `exports == window` if `bpgdec.js/bpgdec8.js/bpgdec8a.js` is included on a page using a script tag.
- Tell git to ignore object files and other compilation output.
- Increase the C stack size, since the entire BPG file has to be copied to the C stack before decoding can start.
- Add to the linker path so that libbpg can be compiled on more platforms.
- Fix the `install` Makefile target so that it installs `bpgview` if `bpgview` is being compiled.
- Remove deprecated `NO_BROWSER` flag from emscripten arguments.
- Add an `onframe` callback that can control when the next frame of an animation is loaded.

I recognize that this PR is being submitted to an unofficial mirror. However, if I'm really lucky, maybe Fabrice Bellard will notice and incorporate some of these changes.

### CODE REVIEW

**Comment by thomas-huet** [comment]
Hello Collin,
I think a better way to be noticed by Fabrice Bellard is to send him an email at fabrice at bellard dot org. Did you try it?

**Comment by taliastocks** [comment]
Yes, I've sent an email with a patch generated from this pull request, as well as a link to the pull request on github.

**Comment by MrJiangSheng** [comment]
dear sir ,why I can't install it in windows fallow as the introduction?

**Comment by taliastocks** [comment]
This is obviously not the right place to ask that.

**Pull request closed without merging**
